FROM node:22-alpine

WORKDIR /app
COPY package*.json ./
COPY packages/ ./packages/
COPY services/ ./services/
COPY apps/ ./apps/

RUN npm install
WORKDIR /app/apps/web

EXPOSE 3000
CMD ["npm", "run", "dev"]
